name: Release Browser Extension
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write

jobs:
    Publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build web
              run: pnpm buildWebStandalone

            - name: Set ENV date
              id: date
              run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  dist/extension-*.zip
                token: ${{ github.token }}
                tag_name: ${{ steps.date.outputs.date }}
